include: package:flutter_lints/flutter.yaml

linter:
  
  rules:
    curly_braces_in_flow_control_structures: false
    prefer_const_constructors: false
    unnecessary_brace_in_string_interps: false
    prefer_const_literals_to_create_immutables: false
analyzer:
  errors:
     curly_braces_in_flow_control_structures: error
     prefer_const_constructors: error
     unnecessary_brace_in_string_interps: error
     prefer_const_literals_to_create_immutables: error