include: package:flutter_lints/flutter.yaml

linter:
  
  rules:
    curly_braces_in_flow_control_structures: false
    prefer_const_constructors: false
    unnecessary_brace_in_string_interps: false
    prefer_const_literals_to_create_immutables: false
    sort_child_properties_last : false
analyzer:
  errors:
     curly_braces_in_flow_control_structures: warning
     prefer_const_constructors: warning
     unnecessary_brace_in_string_interps: warning
     prefer_const_literals_to_create_immutables: warning
     sort_child_properties_last : warning